services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: kukie
      POSTGRES_USER: kukie
      POSTGRES_PASSWORD: kukie
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data